/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBaseProtonInterface extends Interface {
  getFunction(
    nameOrSignature: "createBasicProton" | "createProton"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createBasicProton",
    values: [AddressLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createProton",
    values: [AddressLike, AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createBasicProton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProton",
    data: BytesLike
  ): Result;
}

export interface IBaseProton extends BaseContract {
  connect(runner?: ContractRunner | null): IBaseProton;
  waitForDeployment(): Promise<this>;

  interface: IBaseProtonInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createBasicProton: TypedContractMethod<
    [creator: AddressLike, receiver: AddressLike, tokenMetaUri: string],
    [bigint],
    "payable"
  >;

  createProton: TypedContractMethod<
    [creator: AddressLike, receiver: AddressLike, tokenMetaUri: string],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createBasicProton"
  ): TypedContractMethod<
    [creator: AddressLike, receiver: AddressLike, tokenMetaUri: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createProton"
  ): TypedContractMethod<
    [creator: AddressLike, receiver: AddressLike, tokenMetaUri: string],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
