/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBaseProton,
  IBaseProtonInterface,
} from "../../../contracts/interfaces/IBaseProton";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenMetaUri",
        type: "string",
      },
    ],
    name: "createBasicProton",
    outputs: [
      {
        internalType: "uint256",
        name: "newTokenId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenMetaUri",
        type: "string",
      },
    ],
    name: "createProton",
    outputs: [
      {
        internalType: "uint256",
        name: "newTokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBaseProton__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseProtonInterface {
    return new Interface(_abi) as IBaseProtonInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBaseProton {
    return new Contract(address, _abi, runner) as unknown as IBaseProton;
  }
}
