/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721Vault,
  IERC721VaultInterface,
} from "../../../contracts/interfaces/IERC721Vault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721Vault__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721VaultInterface {
    return new Interface(_abi) as IERC721VaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC721Vault {
    return new Contract(address, _abi, runner) as unknown as IERC721Vault;
  }
}
